spring:
  application:
    name: transaction-details
  data:
    mongodb:
      uri: mongodb://${MGUSER}:${MGPASWORD}@${MGHOST}:${MGPORT}/?authSource=training
      database: training
      authentication-database: training

management:
  port: 8080
  endpoints:
    web:
      exposure:
        include: "*" 